import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,allTiles,discard,respond,legalActions,winSelf,chooseDiscard,canDiscard,chiBan,roundLabel,seatWind} from '../dist/engine.mjs';
import {scoreHand,flowerItems,paymentFor} from '../dist/scoring.mjs';
function fixture(hands,turn){const g=createGame(99),pool=allTiles(g);g.players.forEach((p,i)=>{p.hand=(hands[i]||[]).map(type=>{const j=pool.findIndex(t=>t.type===type);assert.ok(j>=0);return pool.splice(j,1)[0];});p.melds=[];p.flowers=[];p.discards=[];p.drawn=null;});g.wall=pool;g.turn=turn;g.phase='discard';g.pending=null;g.discardCount=8;g.players.forEach(p=>p.drawCount=2);return g;}
test('bankroll, dealer rotation, round wind and seat flowers are explicit',()=>{let g=createGame(8);assert.ok(g.players.every(p=>p.score===50000));assert.equal(roundLabel(g),'東風東局');g.result={kind:'draw',winners:[]};g=createGame(9,g);assert.equal(g.streak,1);assert.equal(roundLabel(g),'東風東局');for(let i=0;i<15;i++){g.result={kind:'win',winners:[(g.dealer+1)%4]};g=createGame(10+i,g);}assert.equal(roundLabel(g),'北風北局');assert.equal(seatWind(g,0),1);});
test('committed AI kong bypasses lower-priority human chi prompt',()=>{const g=fixture([[1,2,8],[0,0,0],[],[0]],3);discard(g,3,g.players[3].hand[0].id);assert.equal(g.turn,1);assert.equal(g.phase,'discard');assert.equal(g.players[1].melds[0].kind,'kong');assert.equal(legalActions(g).length,0);assert.ok(g.events.some(e=>e.kind==='kong'));});
test('chi swap ban prevents immediate 4 after eating 1 and expires after discard',()=>{const g=fixture([[1,2,3,8],[],[],[0]],3);discard(g,3,g.players[3].hand[0].id);respond(g,'chi',[0,1,2]);const four=g.players[0].hand.find(t=>t.type===3);assert.equal(canDiscard(g,0,four.id),false);const before=JSON.stringify(g);assert.throws(()=>discard(g,0,four.id));assert.equal(JSON.stringify(g),before);assert.equal(chooseDiscard(g.players[0]).type,8);discard(g,0,g.players[0].hand.find(t=>t.type===8).id);assert.deepEqual(g.players[0].banned,[]);assert.equal(g.players[0].hand.some(t=>t.id===four.id),true);});
test('chi ban mirrors across suits, does not wrap suits and includes called tile',()=>{assert.deepEqual(chiBan([0,1,2],0),[0,3]);assert.deepEqual(chiBan([3,4,5],5),[5,2]);assert.deepEqual(chiBan([9,10,11],10),[10]);assert.deepEqual(chiBan([6,7,8],6),[6]);});
test('seat flower scoring is 1 per matching flower; complete group replaces its matching flower',()=>{const g=createGame(2);g.players[0].flowers=[34,35,38].map(type=>({type}));assert.deepEqual(flowerItems(g,0).map(x=>x.tai),[1,1]);g.players[0].flowers=[34,35,36,37].map(type=>({type}));assert.deepEqual(flowerItems(g,0),[{name:'花槓（春夏秋冬）',tai:2}]);});
test('round and seat wind both score, settlement applies 5000 + 500 per tai and dealer streak',()=>{const g=fixture([[0,1,2,3,4,5,9,10,11,18,19,20,27,27,27,31,31],[],[],[]],0);g.players[0].drawn=g.players[0].hand.at(-1).id;g.players[0].flowers=[{type:34}];g.streak=2;const score=scoreHand(g,0,{self:true,tile:{type:31}});assert.ok(score.items.some(x=>x.name==='圈風（東）'));assert.ok(score.items.some(x=>x.name==='門風（東）'));assert.ok(score.items.some(x=>x.name==='正花（春）'));assert.ok(score.items.some(x=>x.name==='門清自摸'&&x.tai===3));const payment=paymentFor(g,0,1,score);assert.equal(payment.amount,5000+(score.tai+5)*500);winSelf(g,0);assert.equal(g.players.reduce((s,p)=>s+p.score,0),200000);assert.equal(g.result.payments.length,3);});
test('nondealer self draw charges dealer bonus only to dealer',()=>{const g=createGame(1);g.streak=1;const score={tai:3,items:[{name:'門清自摸',tai:3}]};assert.equal(paymentFor(g,1,2,score).amount,6500);assert.equal(paymentFor(g,1,0,score).amount,8000);});

function evaluated(hand,{self=false,winning=hand.at(-1),seat=0,setup=()=>{}}={}){const g=fixture([hand,[],[],[]],seat);if(seat!==0){g.players[seat].hand=g.players[0].hand;g.players[0].hand=[];}if(!self){const i=g.players[seat].hand.findIndex(t=>t.type===winning);g.players[seat].hand.splice(i,1);}setup(g);return scoreHand(g,seat,{self,tile:{type:winning}});}
const has=(s,name,tai)=>s.items.some(x=>x.name===name&&x.tai===tai);
test('big three dragons replaces individual dragon triplets',()=>{const s=evaluated([0,1,2,9,10,11,31,31,31,32,32,32,33,33,33,27,27]);assert.ok(has(s,'大三元',8));assert.equal(s.items.some(x=>x.name.startsWith('三元刻')),false);});
test('small three dragons and big four winds exclude their overlapping bonuses',()=>{let s=evaluated([0,1,2,9,10,11,18,19,20,31,31,31,32,32,32,33,33]);assert.ok(has(s,'小三元',4));s=evaluated([27,27,27,28,28,28,29,29,29,30,30,30,0,1,2,31,31]);assert.ok(has(s,'大四喜',16));assert.equal(s.items.some(x=>x.name.startsWith('圈風')||x.name.startsWith('門風')),false);});
test('winning on a discarded triplet does not count that triplet as concealed',()=>{const h=[0,0,0,9,9,9,18,18,18,27,27,27,31,31,31,32,32];let s=evaluated(h,{winning:31});assert.ok(has(s,'四暗刻',5));assert.ok(has(s,'碰碰胡',4));assert.equal(has(s,'五暗刻',8),false);s=evaluated(h,{winning:32});assert.ok(has(s,'五暗刻',8));});
test('pinfu requires a two-sided sequence finish and no flowers',()=>{const h=[0,1,2,3,4,5,9,10,11,18,19,20,21,22,23,6,6];assert.ok(has(evaluated(h,{winning:0}),'平胡',2));assert.equal(has(evaluated(h,{winning:2}),'平胡',2),false);assert.equal(has(evaluated(h,{winning:0,setup:g=>g.players[0].flowers=[{type:35}]}),'平胡',2),false);});
test('suit hands choose one suit award and heavenly win replaces concealed self-draw',()=>{const h=[0,0,0,1,2,3,1,2,3,4,5,6,6,7,8,8,8];const s=evaluated(h,{self:true,setup:g=>{g.discardCount=0;g.totalCalls=0;}});assert.ok(has(s,'清一色',8));assert.ok(has(s,'天胡',24));assert.equal(has(s,'門清自摸',3),false);});
test('eight flowers requires an ordinary winning hand and replaces individual flower awards',()=>{const g=createGame(1);g.players[0].flowers=Array.from({length:8},(_,i)=>({type:34+i}));assert.deepEqual(flowerItems(g,0),[{name:'八仙過海',tai:8}]);});
test('chi with no legal following discard is not offered',()=>{const g=fixture([[1,2,3],[],[],[0]],3);discard(g,3,g.players[3].hand[0].id);assert.equal(g.phase,'discard');assert.equal(g.turn,0);assert.equal(legalActions(g).some(a=>a.kind==='chi'),false);});
test('computer pong immediately wins arbitration over human chi',()=>{const g=fixture([[1,2,8],[0,0,31],[],[0]],3);discard(g,3,g.players[3].hand[0].id);assert.equal(g.phase,'discard');assert.equal(g.turn,1);assert.equal(g.players[1].melds[0].kind,'pong');});
test('hand is never operable during response, opponent turn or settled round',()=>{const g=createGame(1),id=g.players[0].hand[0].id;assert.equal(canDiscard(g,0,id),true);for(const phase of ['response','over']){g.phase=phase;assert.equal(canDiscard(g,0,id),false);}g.phase='discard';g.turn=1;assert.equal(canDiscard(g,0,id),false);});
